
Import('env')

import glob
ui_files = Glob("*.ui", strings=True)

ui_files_targets = map(lambda(x): x.replace('.ui', '.py'), ui_files)

for i in range(len(ui_files)):
	env.Command(
  		target = ui_files_targets[i],
		source = ui_files[i],
		action = "pyuic4 $SOURCE > $TARGET"
	)

