import os
Import('env')

gextract_files = Split("""
	test-gextract.cpp
""")
gextract = env.Program (target='test-gextract',
	source = [gextract_files] + env['ears_files'] + ['actions_file.cpp'],
	LIBS=["marsyas"],
)

basic = env.Program (target='test-basic',
	source = (env['vivi_controller_files'] + ['test-basic.cpp']
		+ ['ears.o', 'actions_file.o', 'dynamics.cpp']),
	LIBS=["artifastring", "monowav", "marsyas", "gsl", "gslcblas"],
)

basic = env.Program (target='test-stable',
	source = (['test-stable.cpp']
		+ ['ears.o', 'vivi_controller.o', 'actions_file.o', 'dynamics.o']),
	LIBS=["artifastring", "monowav", "marsyas", "gsl", "gslcblas"],
)



#ears_h_files = map(lambda(x): x.replace('.cpp', '.h'),
#	env['ears_files'])


#env.Install('$PREFIX/bin', gextract)
#env.Install('$PREFIX/include/artifastring', [
#env.Install('$PREFIX/include/', artifastring_h_files)
#env.Install('$PREFIX/lib', [
#	'libartifastring.a', 'libmonowav.a'
#])


