import os
Import('env')

gextract_files = Split("""
	test-gextract.cpp
""")

controllerparams = env.Program(target='test-params',
	source = (['controller_params.o'] + ['test-controller-params.cpp'])
)

env.Append(LIBS=["marsyas"])
gextract = env.Program (target='test-gextract',
	source = [gextract_files] + env['ears_files'],
)
gextract = env.Program (target='test-predict-wavfile',
	source = ['test-predict-wavfile.cpp'] + ['ears.o'],
)

env.Append(LIBS=["gsl", "gslcblas"])
#basic = env.Program (target='test-basic',
#	source = (env['vivi_controller_files'] + ['test-basic.cpp']
#		+ ['ears.o', 'dynamics.cpp']),
#)

stable = env.Program (target='test-stable',
	source = (['test-stable.cpp']
                + env['vivi_controller_files']
		+ ['ears.o', 'dynamics.cpp']),
)

pitch = env.Program (target='test-pitch',
	source = (['test-pitch.cpp']
		+ ['ears.o', 'vivi_controller.o', 'controller_params.o', 'dynamics.o']),
)

dampen = env.Program (target='test-dampen',
	source = (['test-dampen.cpp']
		+ ['ears.o', 'vivi_controller.o', 'controller_params.o', 'dynamics.o']),
)


#ears_h_files = map(lambda(x): x.replace('.cpp', '.h'),
#	env['ears_files'])


#env.Install('$PREFIX/bin', gextract)
#env.Install('$PREFIX/include/artifastring', [
#env.Install('$PREFIX/include/', artifastring_h_files)
#env.Install('$PREFIX/lib', [
#	'libartifastring.a', 'libmonowav.a'
#])


